version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STABILITY_API_KEY=${NEXT_PUBLIC_STABILITY_API_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
